### ISSUE TITLE
Better naming / aliasing to interact with the CLI

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/carrot#112]
As described by @michaelgatzen during his first tests of CARROT:

Maybe use identifiers (perhaps in conjunction with types and namespaces)? 

E.g. in the style of `{type}:{namespace}`.{identifier}, like `pipeline:mgatzen.functional_equivalence` or `software:dsp-methods.gatk`

That way it’s immediately clear what type it refers to (software/result/pipeline/template/test/…) and who or what entity is the maintainer, when looking at the namespace

**Comment by KevinCLydon** [comment]
Closed as of release 0.4.0
