### ISSUE TITLE
Current config setup breaks docker-compose and makes running locally difficult

### ISSUE THREAD

**Issue by KevinCLydon** [broadinstitute/carrot#130]
There are a few problems currently preventing easy running of CARROT using docker-compose and that also make running locally just generally a bit of a hassle:

1. Some of the config variables in `config.rs` are set up as required, when they shouldn't be.  For example, `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_TOKEN` are currently required, but should be conditional on `ENABLE_GITHUB_REQUESTS`.
2. It is currently assumed that all users of CARROT will want to utilize the functionality for generating custom docker images from software.  Because of this, it's necessary to provide a registry for the images to be written to, and the cromwell server must have access to it, which I think requires some extra configuration on the cromwell end as well.  We should probably make this functionality optional.
3. The same assumption is made for interacting with google cloud storage.  Reporting and specifying WDLs with gs URIs both require this.  It should be possible to disable both of those features and not require any gcloud credentials.

These changes aren't trivial but they're definitely not anything major. Testing them would probably take a little bit to make sure different configurations of features will work properly and not result in weird errors.  Allowing removing all of them would result in a pretty reduced version of CARROT, but I think that version of it would still have value, in the same way as a local version of cromwell.

**Comment by jonn-smith** [comment]
This seems like an important set of changes to make for ease of use.  Since a user requested them I think they take priority over some other long-term changes we've been planning.
